### ISSUE TITLE
Could not create account

### ISSUE THREAD

**Issue by kushptlapigarage** [qoire/aion-keystore#2]
Following code fails
```
accounts.privateKeyToAccount('0x00ee97c807d20e856796474b139f3a2648c2fb14e6579154e4c6648d6958f7a78da0078c9c5e33c005c2833a336f89ec3d7188191184908c5086d9f472733d8e');
Error: bad secret key size
```

Using aion-keystore veresion ```^0.0.2``` on Mac OS

**Comment by aion-kelvin** [comment]
Can you use https://github.com/aionnetwork/aion_web3 instead?  I believe all functionality of this package is available in that package.
